[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"


[features]
resolution = true
skip-lint = false

[programs.localnet]
pollana = "JAVuBXeBZqXNtS73azhBDAoYaaAFfo4gWXoZe2e7Jf8H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run ts-mocha"
